services:
    php:
        user: app
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
            args:
                USER_ID: ${USER_ID:-1000}
                DOCKER_PHP_VERSION: ${DC_PHP_VERSION:-8.5}
        ports:
            - "8337:8337"
        networks:
            - sio_test_network
        volumes:
            - ./:/app:rw
        environment:
            - APP_ENV=dev
        # depends_on:
        #     - postgres
        healthcheck:
            # prettier-ignore
            test:
                ["CMD", "php", "-r", "file_get_contents('http://localhost:8337');"]
            interval: 2s
            timeout: 10s
            retries: 15
            start_period: 5s

networks:
    sio_test_network:
