# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
#:schema ./.schema/mago.json

php-version = "8.5.0"

[source]
workspace = "."
paths = ["./src", "./config", "./tests"]
includes = ["vendor"]
excludes = []

[formatter]
preset = "default"
print-width = 120
align-assignment-like = true
always-break-attribute-named-argument-lists = true
always-break-named-arguments-list = true
array-table-style-alignment = true
preserve-breaking-argument-list = true
preserve-breaking-parameter-list = true
preserve-breaking-member-access-chain = true
first-method-chain-on-new-line = false
method-chain-breaking-style = "same_line"

[linter]
integrations = ["symfony"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
