#:schema https://mise.jdx.dev/schema/mise.json

[env]
_.file = [".env", ".env.local"]
COMPOSE_FILE = "./docker-compose.yaml"
DOCKER_PHP_VERSION = "8.5"
DOCKER_PHP_CONTAINER_NAME = "sio_test"

[tools]
hurl = "latest"
mago = "latest"

# section:tasks
[tasks]
[tasks.docker-compose-down]
description = "Stops all containers"
file = "./.mise/scripts/docker-compose-down.sh"

[tasks.docker-compose-up]
description = "Runs specified containers (all by default) in detached mode"
depends = ["docker-compose-down"]
file = "./.mise/scripts/docker-compose-up.sh"

[tasks.docker-compose-logs]
description = "Shows all containers logs in following mode"
env = { COMPOSE_FILE = "./docker-compose.yaml" }
run = "docker compose logs --follow"

[tasks.docker-cli]
description = "Installs composer dependencies"
wait_for = ["docker-compose-up"]
run = "./.mise/scripts/cli.sh"

[tasks.docker-healthcheck]
description = "Waits for containers to be healthy"
wait_for = ["docker-cli composer install"]
file = "./.mise/scripts/docker-healthcheck.sh"

[tasks.test-http]
description = "Runs HTTP tests with HURL"
env = { HURL_VARS_FILE = "{{ config_root }}/hurl.env", HURL_REQUESTS_FILES = "requests.hurl", DC_RUN_SILENT = "1" }
run = [
  { task = "docker-compose-up" },
  { task = "docker-cli composer install" },
  { task = "docker-healthcheck" },
  "hurl ${HURL_REQUESTS_FILES} --variables-file ${HURL_VARS_FILE:-hurl.env}"
]
