#:schema https://mise.jdx.dev/schema/mise.json

[tools]
hurl = "latest"
lefthook = "latest"
mago = "latest"

[env]
_.path = ["./bin", "./vendor/bin"]
_.file = [".env", ".env.local", "./.env.*.local"]
DC_SERVICES = "php;database"
DC_PHP_VERSION = "8.5"
COMPOSE_FILE = "{{ config_root }}/compose.yaml"
# Hurl
HURL_REQUESTS_FILES = "{{ config_root }}/tests/http/requests.hurl"
HURL_VARS_FILE = "{{ config_root }}/tests/http/hurl.env"
# Pest
PHP_TEST_RUNNER = "vendor/bin/pest"

[shell_alias]
pest = """pest --test-directory="tests/Php""""
composer = """mise docker:compose:exec --service php -- composer"""
console = """mise docker:compose:exec --service php -- bin/console"""

# INFO: Automatically updates git hooks on hook config change
[[watch_files]]
patterns = ["./.config/lefthook.yaml"]
run = "lefthook install"

# INFO: Automatically updates permissions on mise task scripts
# WARN: Think about how safe is this
[[watch_files]]
patterns = [".mise/tasks/**/*"]
run = """
IFS=':' read -ra FILES <<< "$MISE_WATCH_FILES_MODIFIED"
UNIQUE_FILES=$(for f in "${FILES[@]}"; do realpath "$f"; done | sort -u)
chmod ug+x $UNIQUE_FILES
"""
