# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: REST API Tests

on:
    pull_request:
        branches:
            - main

jobs:
    tests_api:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: jdx/mise-action@v4
              with:
                  cache: true

            - name: Set USER_ID
              run: echo "UID=$(id -u)" >> $GITHUB_ENV

            - name: Run REST API tests
              env:
                  USER_ID: ${{ env.UID }}
              run: mise run tests:**api
